### ISSUE TITLE
probable bug in file carota-debug.js

### ISSUE THREAD

**Issue by fpolito** [danielearwicker/carota#37]
Hi Daniel

first thanks for your good job!

I have notice that maybe there is a bug in your last release of Carota.

The error occur in file carota-debug.js at line 246
...
this.words = per(characters(runs)).per(split()).map(function(w) {
...
in the console of Google Chrome the message is
Uncaught TypeError: per is not a function

So my workaruond is to use the file carota-debug.js that I have copied from the folder where your demo site is (http://earwicker.com/carota/carota-debug.js) and work good!

I did a match of the 2 files carota-debug.js the and I have discovered that there is a difference at line 26

in your file is
path = path.split('/');

in the file of the repository is
path = path.split(/[\\/]/);

May be here is the error.
So please put the right files in repository.
--------------------------------
I have tested all in a PC with windows 10, Xampp, Node.js

I suggest you to write a paragraph about the instruction to install Carota, because is not so clear (I spent a lot of time to make it to work properly).
bye Francesco

**Comment by nickbuddendotcom** [comment]
+1. @fpolito should maybe fork...appears to no longer be maintained here.

**Comment by nickbuddendotcom** [comment]
@fpolito temp fix (change `per` version):

```
{
    "name": "carota",
    "author": "Daniel Earwicker (dan@earwicker.com)",
    "description": "Simple, flexible rich text rendering/editing on HTML Canvas",
    "version": "0.1.4",
    "repository": {
        "type": "git",
        "url": "https://github.com/danielearwicker/carota.git"
    },
    "main": "src/carota.js",
    "scripts": {
        "prepublish": "node make"
    },
    "dependencies": {
        "per": "0.1.7"
    },
    "devDependencies": {
      "webmake": ">=0.3.19",
      "node-minify": ">=0.8.1",
      "express": "3.3.4"
    }
}
```

Proper fix will prolly involve updating carota to the new version of per...

**Comment by danielearwicker** [comment]
That's the right fix, should never have a greater-than version dependency starting with major version zero of course.

Correct that I am not working on this (only spent a few days on it ever, and would probably do it all differently now...), but please fork and play.
