### ISSUE TITLE
Restore the project?

### ISSUE THREAD

**Issue by lavrton** [danielearwicker/carota#52]
Hello, @danielearwicker.

I am a maintainer of https://github.com/konvajs/konva and founder of https://polotno.com/.

I want to have a full rich-text editor in Konva 2d canvas framework, and later I would like to integrate it into Polotno Design Editor.

Furthermore, I was thinking to start canvas-based rich text editor library from the start. But I feel like your project can be a good foundation for it. What I am thinking about is to make a fork and add all other features and change the behavior in some cases. As a developer, I want to invest my time here and as a founder, I am ready to spend some money on it.

Before doing the fork, I want to connect with you, if you would like to collaborate here.

**Comment by danny-dang** [comment]
@lavrton  How's it going building a text editor?

**Comment by lavrton** [comment]
@danny-dang There is a person in Konva community who is making a new rich text editor based on konva framework. You can join discord for that communication: https://discord.gg/8FqZwVT
